## Specifies the url of PubHubs Central; must end with a slash ('/')
#url: https://your-pubhubs-server.com:8080/
# If you want more control, you can configure 'urls' instead:
urls:
  for_browser:  http://localhost:8080
  for_hub: !manual http://host.docker.internal:8080
  #for_hub: !autodetect
  #for_hub: !same_as_for_browser
  for_yivi_app: !autodetect
  # for_yivi_app: !manual http://145.116.129.175:8080
  # for_yivi_app: !manual http://192.168.178.25:8080/ # DEZE AANPASSEN met HOTSPOT IP adres
  #for_yivi_app: !same_as_for_browser

database_location: dev.db  # if not set, in memory database is used

yivi:
  requestor_api_url: http://localhost:8088

pep: { }

# Allowed contexts for embedding the login-flow. This will be the PubHubs global client(8080), allowing it to embed
# itself, in case we need to authenticate for a specific hub and are not (yet) logged in globally.
allowed_embedding_contexts: [localhost:8080]

admins:
  - admin@example.com

hotfixes:
  no_secure_cookies: true # browsers should allow secure cookies on insecure localhost, but they don't
