//! Endpoints provided by a hub
use actix_web::http;
use serde::{Deserialize, Serialize};

use crate::api::*;
use crate::id;
use crate::misc::serde_ext::{self, bytes_wrapper::B64UU};

/// Basic information advertised by the hub
pub struct InfoEP {}
impl EndpointDetails for InfoEP {
    type RequestType = NoPayload;
    type ResponseType = Result<InfoResp>;

    const METHOD: http::Method = http::Method::GET;
    const PATH: &'static str = ".ph/info";
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
#[must_use]
pub struct InfoResp {
    /// Key used by the hub to sign requests to the other hubs with
    ///
    /// (Not currently returned by actual hubs.)
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verifying_key: Option<VerifyingKeyBytes>,

    /// String describing the hub version, likely the result of `git describe --tags`
    pub hub_version: String,

    /// URL to this hub's client
    pub hub_client_url: url::Url,

    /// The database engine the hub is currently running on, which lets us track which hubs
    /// have completed the sqlite3 -> postgres migration.  Defaults to [`DatabaseEngine::Unknown`]
    /// for hubs predating this field.
    #[serde(default)]
    pub database_engine: DatabaseEngine,

    /// Changeable information about this hub.
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dynamic: Option<DynamicHubInfo>,
}

/// Database engine a hub runs on; reported by [`InfoResp::database_engine`].
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum DatabaseEngine {
    /// Synapse's built-in sqlite3 database: a hub that has not (yet) migrated.
    Sqlite3,

    /// The embedded postgres database: a hub that has completed the migration.
    Postgres,

    /// Reported by hubs predating this field, or running an unrecognised engine.  Also the
    /// catch-all for any engine string we don't know, so a new engine never fails to parse.
    #[default]
    #[serde(other)]
    Unknown,
}

/// Type for [`InfoResp::dynamic`]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
#[must_use]
pub struct DynamicHubInfo {
    /// The last time these settings were reloaded by the hub, which a hub generally does every
    /// minute.
    pub last_reload: NumericDate,

    /// Hub settings set by admin
    pub settings: serde_json::Value,
}

/// Endpoint that start the authentication of a (not yet existing) user
pub struct EnterStartEP {}
impl EndpointDetails for EnterStartEP {
    type RequestType = NoPayload;
    type ResponseType = Result<EnterStartResp>;

    const METHOD: http::Method = http::Method::POST; // to dissuade caching
    const PATH: &'static str = ".ph/enter-start";
}

/// What's returned by [`EnterStartEP`].
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
#[must_use]
pub struct EnterStartResp {
    /// Opaque state that needs to be send to the [`EnterCompleteEP`] later on
    pub state: EnterState,

    /// Opaque number used only once to be included in the hub pseudonym package.
    pub nonce: EnterNonce,

    /// The HHPP signature scheme this hub can verify.  The global client must relay it to
    /// [`HhppReq::hhpp_signature_scheme`](crate::api::phc::user::HhppReq::hhpp_signature_scheme) so
    /// PHC signs with a key the hub accepts.  Absent ⇒
    /// [`Ed25519`](sso::HhppSignatureScheme::Ed25519), for hubs predating the hybrid migration.
    #[serde(default, skip_serializing_if = "sso::HhppSignatureScheme::is_default")]
    pub hhpp_signature_scheme: sso::HhppSignatureScheme,

    /// Per-session key the hub uses to bind its id; see [`HubMacKey`].  Relayed by the global client to
    /// [`EhppReq::hub_mac_key`](crate::api::tr::EhppReq::hub_mac_key).  `None` for hubs predating the
    /// check.
    ///
    /// TODO: remove once all hubs are >3.4.0.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hub_mac_key: Option<HubMacKey>,
}

/// Type of [`EnterStartResp::state`]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(transparent)]
pub struct EnterState {
    pub(crate) inner: B64UU,
}

impl From<B64UU> for EnterState {
    fn from(inner: B64UU) -> Self {
        Self { inner }
    }
}

/// Type of [`EnterStartResp::nonce`]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(transparent)]
pub struct EnterNonce {
    pub(crate) inner: B64UU,
}
impl From<B64UU> for EnterNonce {
    fn from(inner: B64UU) -> Self {
        Self { inner }
    }
}

/// Symmetric key to bind the hub id, but 'blind' the hub id from PHC.
///
/// The [`HubMacKey`] is randomly generated by the hub for each call to [`EnterStartEP`], stored in
/// the hub-encrypted [`EnterStartResp::state`] — which, unlike the [`EnterNonce`], never transits
/// the transcryptor or PHC — and returned to the global client via [`EnterStartResp::hub_mac_key`].
/// The global client relays it to the transcryptor via
/// [`tr::EhppReq::hub_mac_key`](crate::api::tr::EhppReq::hub_mac_key).
///
/// The transcryptor uses the [`HubMacKey`] to HMAC the hub id it pseudonymises for (see
/// [`HubMacKey::mac`]).  The mac is passed via the [`sso::EncryptedHubPseudonymPackage`] to PHC,
/// which includes it in the [`sso::HashedHubPseudonymPackage`] that eventually ends up back at the
/// hub, via [`EnterCompleteReq`]. The hub can then check the mac is indeed the mac of its own hub
/// id, using the [`HubMacKey`] recovered from its state.
///
/// This [`HubMacKey`] is known to the hub and the global client, but must remain hidden from PHC.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, zeroize::ZeroizeOnDrop)]
#[serde(transparent)]
pub struct HubMacKey {
    inner: B64UU<serde_ext::ByteArray<32>>,
}

impl HubMacKey {
    /// Generates a new random key.
    pub fn random() -> Self {
        Self {
            inner: serde_ext::ByteArray::<32>::from(crate::misc::crypto::random_32_bytes()).into(),
        }
    }

    /// Macs a `hub_id`: returns `HMAC-SHA256(self, hub_id)`, the hub id blinded so PHC can not
    /// see what hub is being visited.
    pub fn mac(&self, hub_id: &id::Id) -> id::Id {
        use hmac::Mac as _;

        // Standalone HMAC-SHA256 (cf. `jwt::HS256`), vector-locked with the Python hub's
        // `verify_hub_id_mac` via the `hub_id_mac_vector` test — kept off the JWT layer on purpose.
        let mut mac = hmac::Hmac::<sha2::Sha256>::new_from_slice(self.inner.as_slice())
            .expect("HMAC did not accept key - but it should accept any key");
        mac.update(hub_id.as_slice());
        let bytes: [u8; 32] = mac.finalize().into_bytes().into();
        id::Id::from(bytes)
    }
}

/// Endpoint to complete user authentication
pub struct EnterCompleteEP {}
impl EndpointDetails for EnterCompleteEP {
    type RequestType = EnterCompleteReq;
    type ResponseType = Result<EnterCompleteResp>;

    const METHOD: http::Method = http::Method::POST; // to dissuade caching
    const PATH: &'static str = ".ph/enter-complete";
}

/// What's sent to [`EnterCompleteEP`]
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub struct EnterCompleteReq {
    /// The one you got from [`EnterStartResp::state`]
    pub state: EnterState,

    /// The hashed hub pseudonym package obtained from pubhubs central.
    /// Should include the [`EnterStartResp::nonce`] belonging to the [`Self::state`].
    pub hhpp: Signed<sso::HashedHubPseudonymPackage>,
}

/// What's returned by [`EnterCompleteEP`].
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
#[must_use]
pub enum EnterCompleteResp {
    /// Start again at [`EnterStartEP`]
    RetryFromStart,

    Entered {
        /// Synapse access token
        access_token: String,

        /// Device ID.  (Not sure if it's useful to the global client, though.)
        device_id: String,

        /// True if this is the first time this user enters this hub.
        new_user: bool,

        /// Matrix id to use in combination with the [`Self::Entered::access_token`] to log in.
        mxid: String,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Shares a fixed HMAC-SHA256 vector with `pubhubs_hub/test/hub_id_mac_test.py`, locking the
    /// transcryptor's [`HubMacKey::mac`] and the hub's Python check to the same bytes.
    #[test]
    fn hub_id_mac_vector() {
        // key = 32 bytes of 0x01, hub id = 32 bytes of 0x02 (both unpadded base64url)
        let key: HubMacKey =
            serde_json::from_str("\"AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE\"").unwrap();
        let hub_id = id::Id::from([2u8; 32]);
        let expected: id::Id =
            serde_json::from_str("\"cyFAbgyID9kll4mL6zk68q6-1Rq1zfHVLlmR-a-t0t4\"").unwrap();
        assert_eq!(key.mac(&hub_id), expected);
    }
}
