//! Hybrid post-quantum [key encapsulation
//! mechanism](https://en.wikipedia.org/wiki/Key_encapsulation_mechanism)
//! (KEM) based on ML-KEM and ristretto25519.
//!
//! The [`rustls`] package already uses such a hybrid kem (X25519MLKEM768) for PQ KX, but does not
//! expose this to us.  So instead of adding an additional package to pull in X25519MLKEM768,
//! we implement our own hybrid KEM using the implementations of ML-KEM and ristretto25519
//! already in our dependency tree.
//!
//! # Usage
//!
//! To establish a [`SharedSecret`] between, say, Alice and Bob, Alice first generates
//! a **decapsulation key** using [`DecapKey::generate`].  She keeps this key private, but sends
//! the associated **encapsulation key** (obtained via [`DecapKey::encap_key`]) to Bob.
//!
//! Using this [`EncapKey`], Bob can generate a [`CiphertextBytes`]-[`SharedSecret`] pair using
//! [`EncapKey::encap`] **encapsulating** the shared secret into the **ciphertext**.
//!
//! The shared secret can be retrieved, or **decapsulated**, from the ciphertext using Alice's
//! decapsulation key, via [`DecapKey::decap`].

use aws_lc_rs::kem as mlkem;
use curve25519_dalek::ristretto::CompressedRistretto;

use crate::common::elgamal::{self, Encoding as _};
use crate::common::secret;
use crate::misc::error::{Opaque, OPAQUE};
use crate::misc::serde_ext::bytes_wrapper::B64;
use crate::phcrypto;

/// Decapsulation key, the 'private key' of the KEM.  Generate using [`DecapKey::generate`].
#[derive(Debug)]
pub struct DecapKey {
    ml: mlkem::DecapsulationKey,

    /// Cached ML-KEM encapsulation key.  
    ///
    /// The [`mlkem::DecapsulationKey`] type is a bit weird: it either contains just the
    /// decapsulation key (when read from bytes via [`mlkem::DecapsulationKey::new`] *or*
    /// it contains both an encapsulation and decapsulation key (when generated via
    /// [`mlkem::DecapsulationKey::generate`].)
    ///
    /// So to deal with the former case, we include the encapsulation key here as well.
    ml_ek: mlkem::EncapsulationKey,
    ec: elgamal::PrivateKey,
}

/// Encapsulation key, the 'public key' of the KEM.  Can be obtained via [`DecapKey::encap_key`].
#[derive(Debug)]
pub struct EncapKey {
    ml: mlkem::EncapsulationKey,
    ec: elgamal::PublicKey,
}

/// Encoded form of [`DecapKey`].
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, zeroize::ZeroizeOnDrop)]
pub struct DecapKeyBytes {
    ml: B64,
    /// ML-KEM encapsulation-key bytes; see [`DecapKey::ml_ek`].
    ml_ek: B64,
    /// Scalar bytes.
    ec: B64,
}

/// Encoded form of [`EncapKey`].
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct EncapKeyBytes {
    ml: B64,
    /// [`CompressedRistretto`] bytes.
    ec: B64,
}

/// Encrypted [`SharedSecret`].  Create using [`EncapKey::encap`] and
/// decrypt using [`DecapKey::decap`].
#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct CiphertextBytes {
    ml: B64,
    /// [`CompressedRistretto`] bytes.
    ec: B64,
}

/// Holds shared secrets generated by this KEM.
#[derive(Clone, Debug, zeroize::ZeroizeOnDrop)]
pub struct SharedSecret {
    inner: [u8; 32],
}

impl DecapKey {
    /// Generates a [`DecapKey`].  Expensive.
    pub fn generate() -> Result<Self, Opaque> {
        let ml = mlkem::DecapsulationKey::generate(&mlkem::ML_KEM_768)?;
        Ok(Self {
            ml_ek: ml.encapsulation_key()?,
            ml,
            ec: elgamal::PrivateKey::random(),
        })
    }

    /// Returns the associated [`EncapKey`].  Deterministic and cheap.
    pub fn encap_key(&self) -> EncapKey {
        // Getting the encapsulation_key via self.ml.encapsulation_key is fastest,
        // but it might not be there.
        let ml = self.ml.encapsulation_key().unwrap_or_else(|_| {
            mlkem::EncapsulationKey::new(
                &mlkem::ML_KEM_768,
                self.ml_ek
                    .key_bytes()
                    .expect("failed to retrieve encapsulation key bytes")
                    .as_ref(),
            )
            .expect("cached invalid encapsulation key")
        });
        EncapKey {
            ml,
            ec: self.ec.public_key().clone(),
        }
    }

    /// Decapsulates ciphertext, recovering the [`SharedSecret`] within.  Expensive.
    pub fn decap(&self, ct: &CiphertextBytes) -> Result<SharedSecret, Opaque> {
        let ss_ml = self.ml.decapsulate(mlkem::Ciphertext::from(&ct.ml[..]))?;

        let ec_bytes: [u8; 32] = (&ct.ec[..]).try_into()?;
        let pk =
            elgamal::PublicKey::try_from(CompressedRistretto(ec_bytes)).map_err(|()| OPAQUE)?;
        let ss_ec = self.ec.shared_secret(&pk);

        Ok(phcrypto::kem_shared_secret(&ss_ml, &ss_ec))
    }

    /// Encodes for storage.
    pub fn encode(&self) -> Result<DecapKeyBytes, Opaque> {
        Ok(DecapKeyBytes {
            ml: to_b64(self.ml.key_bytes()?.as_ref()),
            ml_ek: to_b64(self.ml_ek.key_bytes()?.as_ref()),
            ec: to_b64(self.ec.as_scalar().to_bytes()),
        })
    }
}

impl DecapKeyBytes {
    /// Decodes into [`DecapKey`].  Expensive.
    pub fn decode(&self) -> Result<DecapKey, Opaque> {
        Ok(DecapKey {
            ml: mlkem::DecapsulationKey::new(&mlkem::ML_KEM_768, &self.ml[..])?,
            ml_ek: mlkem::EncapsulationKey::new(&mlkem::ML_KEM_768, &self.ml_ek[..])?,
            ec: elgamal::PrivateKey::from_slice(&self.ec[..]).ok_or(OPAQUE)?,
        })
    }
}

impl EncapKey {
    /// Creates a [`SharedSecret`] and a [`CiphertextBytes`] encapsulating it.  Expensive.
    pub fn encap(&self) -> Result<(CiphertextBytes, SharedSecret), Opaque> {
        let (ct_ml, ss_ml) = self.ml.encapsulate()?;

        let ephemeral_sk = elgamal::PrivateKey::random();
        let ss_ec = ephemeral_sk.shared_secret(&self.ec);

        let ct = CiphertextBytes {
            ml: to_b64(ct_ml),
            ec: to_b64(ephemeral_sk.public_key().to_bytes()),
        };
        Ok((ct, phcrypto::kem_shared_secret(&ss_ml, &ss_ec)))
    }

    /// Encodes this key.  Cheap.
    pub fn encode(&self) -> Result<EncapKeyBytes, Opaque> {
        Ok(EncapKeyBytes {
            ml: to_b64(self.ml.key_bytes()?.as_ref()),
            ec: to_b64(self.ec.to_bytes()),
        })
    }
}

impl EncapKeyBytes {
    /// Decodes into [`EncapKey`].
    pub fn decode(&self) -> Result<EncapKey, Opaque> {
        Ok(EncapKey {
            ml: mlkem::EncapsulationKey::new(&mlkem::ML_KEM_768, &self.ml[..])?,
            ec: {
                let bytes: [u8; 32] = (&self.ec[..]).try_into()?;
                elgamal::PublicKey::try_from(CompressedRistretto(bytes)).map_err(|()| OPAQUE)?
            },
        })
    }
}

impl From<[u8; 32]> for SharedSecret {
    fn from(inner: [u8; 32]) -> Self {
        Self { inner }
    }
}

impl secret::DigestibleSecret for SharedSecret {
    fn as_bytes(&self) -> &[u8] {
        &self.inner
    }
}

/// Wraps a byte slice as a base64-serializing blob.
fn to_b64(bytes: impl AsRef<[u8]>) -> B64 {
    serde_bytes::ByteBuf::from(bytes.as_ref().to_vec()).into()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::common::secret::DigestibleSecret as _;

    #[test]
    fn hybrid_roundtrip() {
        let dk = DecapKey::generate().unwrap();
        let ek = dk.encap_key();

        let (ct, ss_sender) = ek.encap().unwrap();
        let ss_recipient = dk.decap(&ct).unwrap();

        assert_eq!(ss_sender.as_bytes(), ss_recipient.as_bytes());
    }

    #[test]
    fn encode_decode_roundtrip() {
        let dk = DecapKey::generate().unwrap();

        // Decapsulation key survives an encode/decode trip (config persistence).
        let dk2 = dk.encode().unwrap().decode().unwrap();
        // Encapsulation key likewise (wire), and both keys still agree on a fresh secret.
        let ek = dk.encap_key().encode().unwrap().decode().unwrap();

        let (ct, ss_sender) = ek.encap().unwrap();
        assert_eq!(ss_sender.as_bytes(), dk2.decap(&ct).unwrap().as_bytes());
    }

    #[test]
    fn bytes_serde_roundtrip() {
        let dk = DecapKey::generate().unwrap();
        let ek_bytes = dk.encap_key().encode().unwrap();

        let json = serde_json::to_string(&ek_bytes).unwrap();
        let ek_bytes2: EncapKeyBytes = serde_json::from_str(&json).unwrap();

        assert_eq!(ek_bytes, ek_bytes2);
    }

    #[test]
    fn decap_key_bytes_serde_roundtrip() {
        let dk_bytes = DecapKey::generate().unwrap().encode().unwrap();
        let json = serde_json::to_string(&dk_bytes).unwrap();
        // DecapKeyBytes isn't PartialEq, so round-trip via re-serialize.
        let dk_bytes2: DecapKeyBytes = serde_json::from_str(&json).unwrap();
        assert_eq!(serde_json::to_string(&dk_bytes2).unwrap(), json);
    }

    #[test]
    fn ciphertext_bytes_serde_roundtrip() {
        let dk = DecapKey::generate().unwrap();
        let (ct, _) = dk.encap_key().encap().unwrap();
        let json = serde_json::to_string(&ct).unwrap();
        let ct2: CiphertextBytes = serde_json::from_str(&json).unwrap();
        assert_eq!(ct, ct2);
    }

    /// Pins encoding.  (See [`print_test_vectors`] for the source.)
    #[test]
    fn pinned_vectors() {
        use base64ct::Encoding as _;

        const DK_JSON: &str = r#"{"ml":"3DBqLMQqsYs+9FqDPBBIXrqLCWjDN6Z0ShVP5WOQInlm60xfKQNfYQyQkJMhJ8MMjZSkFTmKN8amGoeBXIPO7re8B6XPdGwHAvtc4tCczJqrzpcs/9wJnYQmWLVJbHAsZTmPlxcNoRpTeLldBWMZM/SrmgM2TNBasTIh3em/bgUVmkuc56IbbFAV4ACShUR12MMzlOoP6HFMmrrOBTmfHscla/Mfm0ddhgIrroZUpKmTWYaeKWqcxGF3qlYaBjBL8BujiyUA+MgymjDCCOSFa+CKiUGXTtee2+IYO8l26zvCXmRChqK9+tqR6BFKL3d7dnIge5dgiIOQfqiASzphO+USttx6ZeU0DUl2SahtM+ooyfuB17RSefFjm0IN/ZxtldmkW8lioVJB9+Z+sKpD/0OEEcW8RQqXY8hKNBqVY2YTMPsAgEOcvJhEbByB0GUPrEV/xSkW4Gs2B6dO5RoE8rchHqHHGIEy8jq9QJtej1xuxzIuqBlzTDYAjvWThYq7QGqXXqmzOpMwfPwnK1fOMwA2ScI5dOAlsxyAemDOCioxCedGuSJ2aPFQZXI7fFYHvDBngccjy4ssvnnG+6U0V6YD8glwgPZU/Wq7REZwOhaccma5odmzv2Y5XDAW1MuIyNkj23ddp6UlUUuGREVGPdzCqymAC0o6M9Zk5XCpxNJ0bitcbTckJXLKpvV92SnEXCdodRoYOZcfG0Zdszi5gQMl9SdWbjGE02UinDUQ5sfEbLtPgnxrXFaJFNRy7HGbJwyD36AWzwIkXFMxI9ecVVRhoTBJ3IU0UaxA63gk6TOoggaIpxqck7OsvVy10wGa/EK114RkU0yis2AS4Do35YMQjLBtR2hzxxQNqEtaYgagfYh6/KJC2CICrQeRKLVtREYB7bVqyAnAQRlLcIOZvmJyDljKwWyZlnl4Z9HMpbRApSRXaaOZohGfBAJWHNDK6IWO1GcSlAlZfFwAVLIWk/eAall2lbImBXAhJFp9Jxe+SaZNOWyxHrlEqLHJDZWRwbJA14UVjPYpXgLA/UIRqrDIX0aZ+4Cqa1tduhiedUOhTXG+E/kGITl/gTEK1CFBvfOrBDNPOwJGjBJiTRVA8MtBAwWr1OcI69OANhcstWyac0Y677iDp0UI2IUQXlKKQvdEsNpBsNe789aqlxK+zJom17Gr1iiGoyJP0IVHvtyjEywOx1YfdOYD5NUriuczMGIAN6ylHHbI11FKGXURJ9IPGYAwk3qCD4kZlQMxSViHbKmxkSOfTNWjaxYLX7iKF2W2K1ZVmASO9lVQMEQRB4pd9KE+4aUbyvAfG2GehieD5YJ9C/GEJZYCRptSwxewuem8LhoiSLkYVZRR4NnCuyqYAaFxyhYjd6kMxFg3WBwOJ1ywNOpCLrvGm3Kmg8cYoNtzeXPGe7B0Vkqb4auj5lIA+9qnA9dKpNcrKlJUXuIo50MAsHGAGfgahvmfSOe4kaNIMDgvCohVu9YH2DCoJbyDvGxy0JVfxYCYrIBRjMQJ6dZ4J2uT2VOIHCRnTpO/v+TH0Iu93tK3KdRKgoPCDLVZR2Udv6kI8tEGY9c6YmmL8vWxssN2RHdOQdkRADxy0WqE5ol+k0o7x4o8dyCN7uExNOxsoXCc0rteLEQgONE0qtiF4RcVYAihYclmv7F+XgdmMpjDobhSqRgS4NgvhzFMLFUSI7OEoxKJndiS59mRnCckuYzJDncQ0ijCrSF3cMFDgshEyjhon1QTkRu4Y3w1dHO44oOFH9GFm9Fl7SgcsaIOYaGqrXGZLsjJ3tUPwiWiEQZ3quWvVmxDfRmnl6Rb+zy9ZcABJOtGTwomEMQyXBAfT6UU58xftLM37kgyQzVmBtFQ4hx1MGpcibm2hbGNzaG6gbq0EYYRDpiMdwxQ4YgJ7Psxy+yFgGhoFCRei3M/LbGA56fD34hmzPkOhOO5h/AfGCfCkvklT5YLLki2OCUjwyJzuoPKC0lNdvU8peGbzjTLS4IokipdaEHLP2ZRl7EVIqC0Rzt5g+qvQBvHIDM0qUuUO/CXpay5rDkfUMrDeYGE2Xd3fIprEHqv7oNF8xtgVJwKZXQXBcAjJhd46VTGlwgPH8qrzNZUiHRaV4AtHgluw8UdTai1vui0EVBIFSlpiBmc75F0NnUDisbGMUIryOUdVFULOjVst6xJ6VYRYhdkIHt/JVksb1LNHowvugwaT3Nah9G+gMDOmncFmkV363supwMFoMcb/zy/ZMBZYzkJtoMSbmSVaVgOA3iulSB3WpkxRYuSmZwIOJhv4nuTzCtFRpaGzxSacwbLsLFY19povwAcuhge5CpN1vVtL5kbIquCFQI9WCdHYECE2TxAwXh4UWFxy5CfbkmSroFyRRVhnjGuKZDME0ltBRJoD2LP0taEftBKCgRa/UZZr3RUkPcVZ/evG5I2unIv69CZ0GHKBRCY0omzxmF6hqCneeYFaGQpfhMpJQeFj/V+UdUv2VfMUqMFYsVfW4tP2qFGAqV4t3YFnhRLWfzPjAc6FvKT0aU1qjQp3aC72vFppiyyAcoQADcx7xmLy4XB03GQyCCyVPRjVwK1rJpzfJB0i9zOzyQVe7ks2buXeCauoZVyEcgETuFi6sFd5SLE7nXDtYUo3FCTzDy/r5HLAecQjUF7h8qkzSFauWfDmVmLjjxa04GEJHdWSAiZTWg4OUVY3KdTyxMMR6tF9ghfcYslFru3KzQTtiibkqtmlGacCoVDbzefjLG7/naGbZidggck9lJd4sTCbBqIy2y+7KM2edgu3MA6qXBt/8Q7dbWho7Z3sGBVexeTIYiWRDZAfsUEHyXKWkhLOZo/zZOIfNiLvzBWhBCSGQJ9F4MLmeB0aew7+gixHWKIn3iNoIJ/m5elaUJenbIn8/abeMpyJXCL0lofrOxoMAwpg3WzLPuaxDadR1J/v5dGATGcq3UfoIOv3NaDzpmnrqsvI4CHwJF5mbRBj+Q8m3g40iG72zinJDFs0gR9yXclnbvGe/GFNOUI+eI/VpOctsEOC3pACWgoQQxePyRRlvF/jxWdPKRJd0WcBbQZ/IBsvnaEQ6ByY5dhYGdHIFGkl/LiwDoZhXxkP5QpmcPFg758Q0uQ7Z2UPDZ4/n21LUXGOJs2xIqGKOHyzDiRnG8y32s+cRhORJ8WZDiReTJcvCNz0uNFq15r1mii8yJMObgZC6GSDaji","ml_ek":"v+TH0Iu93tK3KdRKgoPCDLVZR2Udv6kI8tEGY9c6YmmL8vWxssN2RHdOQdkRADxy0WqE5ol+k0o7x4o8dyCN7uExNOxsoXCc0rteLEQgONE0qtiF4RcVYAihYclmv7F+XgdmMpjDobhSqRgS4NgvhzFMLFUSI7OEoxKJndiS59mRnCckuYzJDncQ0ijCrSF3cMFDgshEyjhon1QTkRu4Y3w1dHO44oOFH9GFm9Fl7SgcsaIOYaGqrXGZLsjJ3tUPwiWiEQZ3quWvVmxDfRmnl6Rb+zy9ZcABJOtGTwomEMQyXBAfT6UU58xftLM37kgyQzVmBtFQ4hx1MGpcibm2hbGNzaG6gbq0EYYRDpiMdwxQ4YgJ7Psxy+yFgGhoFCRei3M/LbGA56fD34hmzPkOhOO5h/AfGCfCkvklT5YLLki2OCUjwyJzuoPKC0lNdvU8peGbzjTLS4IokipdaEHLP2ZRl7EVIqC0Rzt5g+qvQBvHIDM0qUuUO/CXpay5rDkfUMrDeYGE2Xd3fIprEHqv7oNF8xtgVJwKZXQXBcAjJhd46VTGlwgPH8qrzNZUiHRaV4AtHgluw8UdTai1vui0EVBIFSlpiBmc75F0NnUDisbGMUIryOUdVFULOjVst6xJ6VYRYhdkIHt/JVksb1LNHowvugwaT3Nah9G+gMDOmncFmkV363supwMFoMcb/zy/ZMBZYzkJtoMSbmSVaVgOA3iulSB3WpkxRYuSmZwIOJhv4nuTzCtFRpaGzxSacwbLsLFY19povwAcuhge5CpN1vVtL5kbIquCFQI9WCdHYECE2TxAwXh4UWFxy5CfbkmSroFyRRVhnjGuKZDME0ltBRJoD2LP0taEftBKCgRa/UZZr3RUkPcVZ/evG5I2unIv69CZ0GHKBRCY0omzxmF6hqCneeYFaGQpfhMpJQeFj/V+UdUv2VfMUqMFYsVfW4tP2qFGAqV4t3YFnhRLWfzPjAc6FvKT0aU1qjQp3aC72vFppiyyAcoQADcx7xmLy4XB03GQyCCyVPRjVwK1rJpzfJB0i9zOzyQVe7ks2buXeCauoZVyEcgETuFi6sFd5SLE7nXDtYUo3FCTzDy/r5HLAecQjUF7h8qkzSFauWfDmVmLjjxa04GEJHdWSAiZTWg4OUVY3KdTyxMMR6tF9ghfcYslFru3KzQTtiibkqtmlGacCoVDbzefjLG7/naGbZidggck9lJd4sTCbBqIy2y+7KM2edgu3MA6qXBt/8Q7dbWho7Z3sGBVexeTIYiWRDZAfsUEHyXKWkhLOZo/zZOIfNiLvzBWhBCSGQJ9F4MLmeB0aew7+gixHWKIn3iNoIJ/m5elaUJenbIn8/abeMpyJXCL0lofrOxoMAwpg3WzLPuaxDadR1J/v5dGATGcq3UfoIOv3NaDzpmnrqsvI4CHwJF5mbRBj+Q8m3g40iG72zinJDFs0gR9yXclnbvGe/GFNOUI+eI/VpOctsEOC3pACWgoQQxePyRRlvF/jxWdPKRJd0WcBbQZ/IBsvnaEQ6ByY5dhYGdHIFGkl/LiwDoZhXxkP5QpmcPFg758Q0uQ7Z0=","ec":"u+coWbaISlx2hr7pA5LmWPGg6FZC8pIX+kOC+v/MGgA="}"#;
        const EK_JSON: &str = r#"{"ml":"v+TH0Iu93tK3KdRKgoPCDLVZR2Udv6kI8tEGY9c6YmmL8vWxssN2RHdOQdkRADxy0WqE5ol+k0o7x4o8dyCN7uExNOxsoXCc0rteLEQgONE0qtiF4RcVYAihYclmv7F+XgdmMpjDobhSqRgS4NgvhzFMLFUSI7OEoxKJndiS59mRnCckuYzJDncQ0ijCrSF3cMFDgshEyjhon1QTkRu4Y3w1dHO44oOFH9GFm9Fl7SgcsaIOYaGqrXGZLsjJ3tUPwiWiEQZ3quWvVmxDfRmnl6Rb+zy9ZcABJOtGTwomEMQyXBAfT6UU58xftLM37kgyQzVmBtFQ4hx1MGpcibm2hbGNzaG6gbq0EYYRDpiMdwxQ4YgJ7Psxy+yFgGhoFCRei3M/LbGA56fD34hmzPkOhOO5h/AfGCfCkvklT5YLLki2OCUjwyJzuoPKC0lNdvU8peGbzjTLS4IokipdaEHLP2ZRl7EVIqC0Rzt5g+qvQBvHIDM0qUuUO/CXpay5rDkfUMrDeYGE2Xd3fIprEHqv7oNF8xtgVJwKZXQXBcAjJhd46VTGlwgPH8qrzNZUiHRaV4AtHgluw8UdTai1vui0EVBIFSlpiBmc75F0NnUDisbGMUIryOUdVFULOjVst6xJ6VYRYhdkIHt/JVksb1LNHowvugwaT3Nah9G+gMDOmncFmkV363supwMFoMcb/zy/ZMBZYzkJtoMSbmSVaVgOA3iulSB3WpkxRYuSmZwIOJhv4nuTzCtFRpaGzxSacwbLsLFY19povwAcuhge5CpN1vVtL5kbIquCFQI9WCdHYECE2TxAwXh4UWFxy5CfbkmSroFyRRVhnjGuKZDME0ltBRJoD2LP0taEftBKCgRa/UZZr3RUkPcVZ/evG5I2unIv69CZ0GHKBRCY0omzxmF6hqCneeYFaGQpfhMpJQeFj/V+UdUv2VfMUqMFYsVfW4tP2qFGAqV4t3YFnhRLWfzPjAc6FvKT0aU1qjQp3aC72vFppiyyAcoQADcx7xmLy4XB03GQyCCyVPRjVwK1rJpzfJB0i9zOzyQVe7ks2buXeCauoZVyEcgETuFi6sFd5SLE7nXDtYUo3FCTzDy/r5HLAecQjUF7h8qkzSFauWfDmVmLjjxa04GEJHdWSAiZTWg4OUVY3KdTyxMMR6tF9ghfcYslFru3KzQTtiibkqtmlGacCoVDbzefjLG7/naGbZidggck9lJd4sTCbBqIy2y+7KM2edgu3MA6qXBt/8Q7dbWho7Z3sGBVexeTIYiWRDZAfsUEHyXKWkhLOZo/zZOIfNiLvzBWhBCSGQJ9F4MLmeB0aew7+gixHWKIn3iNoIJ/m5elaUJenbIn8/abeMpyJXCL0lofrOxoMAwpg3WzLPuaxDadR1J/v5dGATGcq3UfoIOv3NaDzpmnrqsvI4CHwJF5mbRBj+Q8m3g40iG72zinJDFs0gR9yXclnbvGe/GFNOUI+eI/VpOctsEOC3pACWgoQQxePyRRlvF/jxWdPKRJd0WcBbQZ/IBsvnaEQ6ByY5dhYGdHIFGkl/LiwDoZhXxkP5QpmcPFg758Q0uQ7Z0=","ec":"oh0u4IZUZXQvAbdr1492EdP0RWVFocTi7vPDCFcLsUc="}"#;
        const CT_JSON: &str = r#"{"ml":"9Wh+jj9EQPYpmg/f3IIDVSt+FzoX2hjlapIFruvffN4Rg/nlQ0tNg286lhA+nvhNX+uavGoFuavTsxThFR0yM8NqALXhXEc3pDjtoFcEzjV+utV/zZ+ifDJ1kF06gtirHdBfOCQZri8m9nJM4/X5Ig1tI/4wdX8c3Jpu3trfnD1en/A/xZ8Do3XTaNK5XJjRY48OU/mk10p0nmvzu5hjL4JeMYSlzFnJWa3/tJTJGLiU9pnkoENss/VEVuDXCY3H2M0/ITt87eTTCW4D0gKrqAyAvxR1URn+5U0Vf68bN8Cz1rs4ypSFnXs2chxh6we7aGBi3e3661aPdaVfXl7mGaQ0KNZGtUEpIUAO9j4FVB5Hj4vQXXB41FeNsvRRWl5CuRQKBgiPvqdfaZPcXT7SizyFuIRZwHOOX1liLiKp/GIXBe4IaR2HHDXpunf07+FDs95QWvyspIAIiwYsLB8w6TNVkasMibC0cTeX0fQWXy0FJ2ZaZ/gBbBZeorYsn0pn6sCr4JTqHBWlyoxk89kk//7CGU1TB7m2RP+xf/+1/Sff0abb2oqDgIeyLF8AP9obeHdry7Yq7SeqUbvp8Vro/P8zkUpUIHFscOOXdNZu+3ZZstxEhDeRIRde+aUYvAwWsyl7cHp966/fGeGguUT1fdEPOCJj3yq7YkOX8Yw69+dtXLU5q4z0RtKpwDyUdvIM3B+p400bh1//BPQ1NLi9YEbRT7FSXivP1QWLGEB0PSo8koeCMpujBx3LafhSV3VQf6G27TvkxeZJ9XC5d8WkkEE6gq6bFWvp26Z0aeug/RY1Q1v9s4caSvzIE+AERJ88mVI8Uv+zbP2UGpYDquhQIglYFUu13/XshBtgkmBT5fw6Cg01dzc+oBwySz/f3FCGU/wCutFvMJFFafJsLSS9iKuC0/zbnH3tB2NF3Atlfq4heHma5mxlo2Wn2pxv/k57fYVw5FF165j4LZnOCUoBwCWz59vsvpfqHI3CNi9BhvehQIlxwyn/vYFcD+VktIJtdTHLfPEXxE5q7IiK6XzQaaa8hCJCeJMjyHbVlT1S225J/e4hy+FDrA3eJPx19e237uqW++LOJSl8SuYMHyKyxrPyQSt8BJKQ801OYRxRX5a1HztL0stF1D2g83puFKBeeWl7S1aOAVneJMZeQyfZQ6yrOjQU9qzdBn3iEwp8XUHcHcak1Bv2+5rU4cfcTUg7QJaHOW5fmEMAo04LO8iSuXRUxzMjAx4ZS9QMey9ojVjzDMHYS5Ma9+3QAtGl1cIDuQpFX9iSnaIFi6DIdM4+E9tOdMPzToGMIDKTR/h9r5wru/6lz+VrpLpeBtyvAJ2gS9e81QP7uqRc5PPDd09pJ5S2d5xO8lEPet1GPRJnUi/wcMXAIYyLHvUteOl39yNorTM4g74+XtnLAkBJGxKZ81o7YoVYAfsr0JWFZniIDGk=","ec":"3H9cUtMTfKCSXae/d2Xb7NYCSeUdUBuIarhJAKb95VM="}"#;
        const SS_B64: &str = "4bpge1ouyjzuygcFzRK62n18Pz8Jidt+Olcpq/02d34=";

        let dk_bytes: DecapKeyBytes = serde_json::from_str(DK_JSON).unwrap();
        let ek_bytes: EncapKeyBytes = serde_json::from_str(EK_JSON).unwrap();
        let ct: CiphertextBytes = serde_json::from_str(CT_JSON).unwrap();
        let ss_expected = base64ct::Base64::decode_vec(SS_B64).unwrap();

        // Serde format is stable: parsed values re-serialize to the captured JSON.
        assert_eq!(serde_json::to_string(&dk_bytes).unwrap(), DK_JSON);
        assert_eq!(serde_json::to_string(&ek_bytes).unwrap(), EK_JSON);
        assert_eq!(serde_json::to_string(&ct).unwrap(), CT_JSON);

        // Encapsulation key derived from the decoded DK matches the captured EK.
        let dk = dk_bytes.decode().unwrap();
        assert_eq!(dk.encap_key().encode().unwrap(), ek_bytes);

        // Decap of the captured ciphertext yields the captured shared secret.
        assert_eq!(dk.decap(&ct).unwrap().as_bytes(), ss_expected.as_slice());
    }

    /// Prints fresh values to regenerate [`pinned_vectors`].  Run with
    /// `cargo test --lib common::kem::tests::print_test_vectors -- --ignored --nocapture`.
    #[test]
    #[ignore]
    fn print_test_vectors() {
        use base64ct::Encoding as _;
        let dk = DecapKey::generate().unwrap();
        let dk_bytes = dk.encode().unwrap();
        let ek_bytes = dk.encap_key().encode().unwrap();
        let (ct, ss) = dk.encap_key().encap().unwrap();

        println!("DK_JSON: {}", serde_json::to_string(&dk_bytes).unwrap());
        println!("EK_JSON: {}", serde_json::to_string(&ek_bytes).unwrap());
        println!("CT_JSON: {}", serde_json::to_string(&ct).unwrap());
        println!(
            "SS_B64:  {}",
            base64ct::Base64::encode_string(ss.as_bytes())
        );
    }

    #[test]
    fn distinct_keys_disagree() {
        let dk = DecapKey::generate().unwrap();
        let other = DecapKey::generate().unwrap();

        let (ct, ss_sender) = dk.encap_key().encap().unwrap();
        // Decapsulating with the wrong key yields a different secret, never an error.
        assert_ne!(ss_sender.as_bytes(), other.decap(&ct).unwrap().as_bytes());
    }
}
