"""Tests for composite ML-DSA-65 + Ed25519 HHPP verification (modules/pubhubs/_composite_hhpp.py).

Coverage:
  - STANDARD scheme verified against the official IETF test vector
    (lamps-wg/draft-composite-sigs, id-MLDSA65-Ed25519-SHA512).
  - BESPOKE scheme verified against a vector generated by the Rust backend
    (src/common/dsa.rs::tests::emit_bespoke_test_vector); no official vector exists for the
    interim empty-ML-DSA-context variant.  This also confirms that pyca/cryptography verifies an
    ML-DSA-65 signature produced by aws-lc-rs with an empty context.
  - The legacy classical EdDSA HHPP (and `alg` confusion) is rejected.

Fixtures live in test/fixtures/.  Regenerate the bespoke one with:
  cargo test --lib dsa::tests::emit_bespoke_test_vector -- --ignored --nocapture
"""

import base64
import hashlib
import json
import os
import sys
import unittest

# Import the module directly rather than via the `pubhubs` package, whose __init__ pulls in
# synapse; the composite logic is self-contained crypto and needs none of it.
sys.path.append("modules/pubhubs")
from _composite_hhpp import (
    BESPOKE_ALG,
    STANDARD_ALG,
    CompositeKey,
    hhpp_jwt,
    parse_verifying_key,
    verify,
    _PREFIX,
    _LABEL,
)

import authlib.jose
from authlib.jose.errors import JoseError
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.asymmetric.mldsa import MLDSA65PrivateKey

_FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")


def _load_fixture(name):
    with open(os.path.join(_FIXTURES, name)) as f:
        return json.load(f)


def _b64u_decode(s):
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


def _b64u_encode(b):
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode("ascii")


class TestStandardScheme(unittest.TestCase):
    """The standard ML-DSA-65-Ed25519 scheme (ML-DSA context = the Label), against the official
    IETF vector."""

    def setUp(self):
        v = _load_fixture("composite_standard_vector.json")
        self.m = base64.b64decode(v["m_b64"])
        self.sig = base64.b64decode(v["sig_b64"])
        pk = base64.b64decode(v["pk_b64"])  # ML-DSA-65 pub (1952) ‖ ed25519 pub (32)
        self.key = parse_verifying_key(
            {
                "ml": base64.b64encode(pk[:1952]).decode(),
                "ed": base64.b64encode(pk[1952:]).decode(),
            }
        )

    def test_official_vector_verifies(self):
        # The standard scheme passes the Label as the ML-DSA context.
        self.assertTrue(verify(self.m, self.sig, self.key, _LABEL))

    def test_empty_context_rejected(self):
        # Verifying with the bespoke (empty) ML-DSA context must fail on a standard signature.
        self.assertFalse(verify(self.m, self.sig, self.key, b""))

    def test_tampered_halves_rejected(self):
        for i in (0, len(self.sig) - 1):  # a byte in the ML-DSA half, and in the ed25519 half
            tampered = bytearray(self.sig)
            tampered[i] ^= 1
            self.assertFalse(verify(self.m, bytes(tampered), self.key, _LABEL))


class TestBespokeScheme(unittest.TestCase):
    """The interim ph-ML-DSA-65-Ed25519 scheme (empty ML-DSA context), against a vector produced by
    the Rust backend — a cross-implementation check (aws-lc-rs signer, pyca verifier)."""

    def setUp(self):
        self.v = _load_fixture("composite_bespoke_vector.json")
        self.key = parse_verifying_key(self.v["verifying_key"])
        self.assertEqual(self.v["alg"], BESPOKE_ALG)

    def test_raw_verify(self):
        header_b64, payload_b64, sig_b64 = self.v["jws"].split(".")
        signing_input = (header_b64 + "." + payload_b64).encode("ascii")
        sig = _b64u_decode(sig_b64)
        self.assertTrue(verify(signing_input, sig, self.key, b""))
        # the standard (Label) context must NOT verify a bespoke signature
        self.assertFalse(verify(signing_input, sig, self.key, _LABEL))

    def test_via_authlib_decode(self):
        # the full hub path: authlib routes alg -> _BespokeComposite -> verify
        claims = hhpp_jwt.decode(self.v["jws"], lambda header, payload: self.key)
        self.assertEqual(claims["msg"], "bespoke composite test vector")

    def test_tampered_jws_rejected(self):
        header_b64, payload_b64, sig_b64 = self.v["jws"].split(".")
        sig = bytearray(_b64u_decode(sig_b64))
        sig[0] ^= 1
        tampered = f"{header_b64}.{payload_b64}.{_b64u_encode(bytes(sig))}"
        with self.assertRaises(JoseError):
            hhpp_jwt.decode(tampered, lambda header, payload: self.key)


class TestStandardSchemeViaAuthlib(unittest.TestCase):
    """Self-consistency check that the standard alg is registered and routed through authlib with
    the Label as ML-DSA context.  (Independent crypto correctness comes from the official vector
    in TestStandardScheme.)"""

    def test_roundtrip(self):
        ml = MLDSA65PrivateKey.generate()
        ed = Ed25519PrivateKey.generate()
        key = CompositeKey(ed=ed.public_key(), ml=ml.public_key())

        header_b64 = _b64u_encode(json.dumps({"alg": STANDARD_ALG}).encode())
        payload_b64 = _b64u_encode(json.dumps({"msg": "standard"}).encode())
        signing_input = (header_b64 + "." + payload_b64).encode("ascii")
        m_prime = _PREFIX + _LABEL + bytes([0]) + hashlib.sha512(signing_input).digest()
        sig = ml.sign(m_prime, _LABEL) + ed.sign(m_prime)  # ML-DSA ctx = Label
        jws = f"{header_b64}.{payload_b64}.{_b64u_encode(sig)}"

        claims = hhpp_jwt.decode(jws, lambda header, payload: key)
        self.assertEqual(claims["msg"], "standard")


class TestRejections(unittest.TestCase):
    def test_classical_eddsa_rejected(self):
        # Hubs upgrade after the central servers, so we no longer accept the classical EdDSA HHPP;
        # EdDSA is not in the allow-list.  (Also covers `alg` confusion such as "none"/HS256.)
        header_b64 = _b64u_encode(json.dumps({"alg": "EdDSA"}).encode())
        payload_b64 = _b64u_encode(json.dumps({"msg": "classical"}).encode())
        jws = f"{header_b64}.{payload_b64}.{_b64u_encode(b'not-a-real-signature')}"
        with self.assertRaises(JoseError):
            hhpp_jwt.decode(jws, lambda header, payload: None)

    def test_both_composite_algs_registered(self):
        registry = authlib.jose.JsonWebSignature.ALGORITHMS_REGISTRY
        self.assertIn(BESPOKE_ALG, registry)
        self.assertIn(STANDARD_ALG, registry)


if __name__ == "__main__":
    unittest.main()
