#!/usr/bin/env sh

# Only run hooks in local development
if [ -n "$CI" ] || [ -n "$GITLAB_CI" ]; then
  exit 0
fi

echo "Running pre-commit checks..."

npx lint-staged

echo "Pre-commit checks complete!"
